// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnstsshscsgkslgpyqyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impuc3Rzc2hzY3Nna3NsZ3B5cXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTEyODIsImV4cCI6MjA3NDE4NzI4Mn0.IOqq7Bxw3aH-RFW8QI7wpRZBvtyiq6ezhX3c2qSxiIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});